package d_dns_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// New creates a new d dns service API client.
func New(transport runtime.ClientTransport, formats strfmt.Registry) *Client {
	return &Client{transport: transport, formats: formats}
}

/*
Client for d dns service API
*/
type Client struct {
	transport runtime.ClientTransport
	formats   strfmt.Registry
}

/*
DeleteRecord delete record API
*/
func (a *Client) DeleteRecord(params *DeleteRecordParams) (*DeleteRecordOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewDeleteRecordParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "DeleteRecord",
		Method:             "DELETE",
		PathPattern:        "/v1/record/{domain}/{type}",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http", "https"},
		Params:             params,
		Reader:             &DeleteRecordReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	return result.(*DeleteRecordOK), nil

}

/*
SaveRecord echos method receives a simple message and returns it the message posted as the id parameter will also be returned
*/
func (a *Client) SaveRecord(params *SaveRecordParams) (*SaveRecordOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewSaveRecordParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "SaveRecord",
		Method:             "POST",
		PathPattern:        "/v1/record",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http", "https"},
		Params:             params,
		Reader:             &SaveRecordReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	return result.(*SaveRecordOK), nil

}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ClientTransport) {
	a.transport = transport
}
