package d_dns_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/muka/ddns/models"
)

// DeleteRecordReader is a Reader for the DeleteRecord structure.
type DeleteRecordReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteRecordReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewDeleteRecordOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewDeleteRecordOK creates a DeleteRecordOK with default headers values
func NewDeleteRecordOK() *DeleteRecordOK {
	return &DeleteRecordOK{}
}

/*DeleteRecordOK handles this case with default header values.

DeleteRecordOK delete record o k
*/
type DeleteRecordOK struct {
	Payload *models.APIRecord
}

func (o *DeleteRecordOK) Error() string {
	return fmt.Sprintf("[DELETE /v1/record/{domain}/{type}][%d] deleteRecordOK  %+v", 200, o.Payload)
}

func (o *DeleteRecordOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.APIRecord)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
