package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// APIRecord Message represents a simple message sent to the Echo service.
// swagger:model apiRecord
type APIRecord struct {

	// Add a PTR (reverse) record
	PTR bool `json:"PTR,omitempty"`

	// TTL time to live of the record
	TTL int32 `json:"TTL,omitempty"`

	// Record Name
	Domain string `json:"domain,omitempty"`

	// Expiration of the record, after which will be removed.
	// Default is 0 for not expiring
	Expires int32 `json:"expires,omitempty"`

	// id
	ID string `json:"id,omitempty"`

	// Record IP address
	IP string `json:"ip,omitempty"`

	// Record Type see https://github.com/miekg/dns/blob/master/types.go#L27
	Type string `json:"type,omitempty"`
}

// Validate validates this api record
func (m *APIRecord) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// MarshalBinary interface implementation
func (m *APIRecord) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *APIRecord) UnmarshalBinary(b []byte) error {
	var res APIRecord
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
